# Generated by Django 5.2 on 2025-04-05 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangeproposal',
            name='ad_receiver',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='ads.ad'),
        ),
        migrations.AddField(
            model_name='exchangeproposal',
            name='ad_sender',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='ads.ad'),
        ),
    ]
