# Generated by Django 5.2 on 2025-04-05 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_exchangeproposal_ad_receiver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangeproposal',
            name='status',
            field=models.CharField(choices=[('О', 'ожидает'), ('П', 'принята'), ('От', 'отклонена')], default='О'),
        ),
    ]
