# Generated by Django 5.2 on 2025-04-19 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_exchangeproposal_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='category',
            field=models.CharField(max_length=200, verbose_name='Категория товара'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='condition',
            field=models.CharField(max_length=200, verbose_name='Состояние товара'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='description',
            field=models.CharField(max_length=500, verbose_name='Описание товара'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='image_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL изображения'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Заголовок объявления'),
        ),
        migrations.AlterField(
            model_name='exchangeproposal',
            name='ad_receiver',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='ads.ad', verbose_name='Обменять на'),
        ),
        migrations.AlterField(
            model_name='exchangeproposal',
            name='ad_sender',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='ads.ad', verbose_name='Ваш товар'),
        ),
        migrations.AlterField(
            model_name='exchangeproposal',
            name='comment',
            field=models.CharField(default='', max_length=500, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='exchangeproposal',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации предложения'),
        ),
        migrations.AlterField(
            model_name='exchangeproposal',
            name='status',
            field=models.CharField(choices=[('waiting', 'ожидает'), ('accepted', 'принят'), ('rejected', 'отклонен')], default='ожидает', verbose_name='Статус предложения'),
        ),
        migrations.AlterUniqueTogether(
            name='exchangeproposal',
            unique_together={('ad_sender', 'ad_receiver', 'status')},
        ),
    ]
