# Generated by Django 5.2 on 2025-04-19 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_alter_ad_category_alter_ad_condition_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='exchangeproposal',
            unique_together={('ad_sender', 'ad_receiver')},
        ),
    ]
