# Generated by Django 5.2 on 2025-04-19 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0005_alter_exchangeproposal_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='exchangeproposal',
            unique_together={('ad_sender', 'ad_receiver', 'status')},
        ),
    ]
