# Generated by Django 5.2 on 2025-04-24 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0007_alter_exchangeproposal_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangeproposal',
            name='comment',
            field=models.CharField(max_length=500, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='exchangeproposal',
            name='status',
            field=models.CharField(choices=[('waiting', 'ожидает'), ('accepted', 'принят'), ('rejected', 'отклонен')], default='waiting', verbose_name='Статус предложения'),
        ),
    ]
